name: sync fork
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync
        run: gh repo sync --branch prettier-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          